services:
  gelato:
    restart: unless-stopped
    build:
      context: .
    # environment:
#      - FFMPEG_CODEC=h264_v4lm2m2
    volumes:
      # - db_data:/data
      # mount /tmp on ram to save read/writes
      - type: tmpfs
        target: /tmp
    devices:
      - /dev/dri:/dev/dri

# volumes:
#   db_data:
